---
driver:
  name: vagrant

platforms:
- name: centos-6.9
  driver_config:
    box: bento/centos-6.9
    require_chef_omnibus: true
    customize:
      cpus: 2
      memory: 2048

suites:
- name: default
  busser:
    sudo: true
  run_list:
    - recipe[java_service_test]
